/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppRoster {
    }
    interface AppRsvp {
        "currentStatus": string;
        "customerId": string;
        "eventId": string;
        "rsvpId": string;
        "teamId": string;
    }
    interface AppRules {
    }
    interface AppSchedule {
    }
    interface AppStandings {
    }
}
export interface AppRsvpCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppRsvpElement;
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {
    }
    var HTMLAppLoginElement: {
        prototype: HTMLAppLoginElement;
        new (): HTMLAppLoginElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRosterElement extends Components.AppRoster, HTMLStencilElement {
    }
    var HTMLAppRosterElement: {
        prototype: HTMLAppRosterElement;
        new (): HTMLAppRosterElement;
    };
    interface HTMLAppRsvpElement extends Components.AppRsvp, HTMLStencilElement {
    }
    var HTMLAppRsvpElement: {
        prototype: HTMLAppRsvpElement;
        new (): HTMLAppRsvpElement;
    };
    interface HTMLAppRulesElement extends Components.AppRules, HTMLStencilElement {
    }
    var HTMLAppRulesElement: {
        prototype: HTMLAppRulesElement;
        new (): HTMLAppRulesElement;
    };
    interface HTMLAppScheduleElement extends Components.AppSchedule, HTMLStencilElement {
    }
    var HTMLAppScheduleElement: {
        prototype: HTMLAppScheduleElement;
        new (): HTMLAppScheduleElement;
    };
    interface HTMLAppStandingsElement extends Components.AppStandings, HTMLStencilElement {
    }
    var HTMLAppStandingsElement: {
        prototype: HTMLAppStandingsElement;
        new (): HTMLAppStandingsElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-login": HTMLAppLoginElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-roster": HTMLAppRosterElement;
        "app-rsvp": HTMLAppRsvpElement;
        "app-rules": HTMLAppRulesElement;
        "app-schedule": HTMLAppScheduleElement;
        "app-standings": HTMLAppStandingsElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppLogin {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppRoster {
    }
    interface AppRsvp {
        "currentStatus"?: string;
        "customerId"?: string;
        "eventId"?: string;
        "onRsvpChanged"?: (event: AppRsvpCustomEvent<any>) => void;
        "rsvpId"?: string;
        "teamId"?: string;
    }
    interface AppRules {
    }
    interface AppSchedule {
    }
    interface AppStandings {
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-login": AppLogin;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-roster": AppRoster;
        "app-rsvp": AppRsvp;
        "app-rules": AppRules;
        "app-schedule": AppSchedule;
        "app-standings": AppStandings;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-login": LocalJSX.AppLogin & JSXBase.HTMLAttributes<HTMLAppLoginElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-roster": LocalJSX.AppRoster & JSXBase.HTMLAttributes<HTMLAppRosterElement>;
            "app-rsvp": LocalJSX.AppRsvp & JSXBase.HTMLAttributes<HTMLAppRsvpElement>;
            "app-rules": LocalJSX.AppRules & JSXBase.HTMLAttributes<HTMLAppRulesElement>;
            "app-schedule": LocalJSX.AppSchedule & JSXBase.HTMLAttributes<HTMLAppScheduleElement>;
            "app-standings": LocalJSX.AppStandings & JSXBase.HTMLAttributes<HTMLAppStandingsElement>;
        }
    }
}
